export const DISHES_LIST_REQUEST = 'DISHES_LIST_REQUEST'
export const DISHES_LIST_SUCCESS = 'DISHES_LIST_SUCCESS'
export const DISHES_LIST_FAIL = 'DISHES_LIST_FAIL'

export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL= 'RESTAURANT_DETAILS_FAIL'

export const CUSTOMER_DISHES_LIST_REQUEST = 'CUSTOMER_DISHES_LIST_REQUEST'
export const CUSTOMER_DISHES_LIST_SUCCESS = 'CUSTOMER_DISHES_LIST_SUCCESS'
export const CUSTOMER_DISHES_LIST_FAIL = 'CUSTOMER_DISHES_LIST_FAIL'
