export const RESTAURANT_SIGNUP_REQUEST = 'RESTAURANT_SIGNUP_REQUEST'
export const RESTAURANT_SIGNUP_SUCCESS = 'RESTAURANT_SIGNUP_SUCCESS'
export const RESTAURANT_SIGNUP_FAIL = 'RESTAURANT_SIGNUP_FAIL'

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST'
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS'
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL'

export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAIL = 'CUSTOMER_LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'
